### ISSUE TITLE
Migration script to upgrade from legacy to main

### ISSUE THREAD

**Issue by BakaKiller** [xSke/PluralKit#203]
Hi there,
I can't find a script to migrate from a legacy version of the bot to the latter, "main" version
Is there anything anywhere ?

Edit : Not sure it matters but I use docker

Thanks for your hard work !

**Comment by acw0** [comment]
Hi! The current bot includes migration code. If you run the latest code on a copy of your database, it should automatically perform all the required migrations.

**Comment by xSke** [comment]
I'm not sure if the database schema changed between the legacy branch and the introduction of the migration system, so it *may* need a couple SQL commands to nudge things along. Try it and let me know?

**Comment by BakaKiller** [comment]
So it does not look like it works. I mean, there are some migreations, but it seems like it is not enough :
```
[2020-07-23 20:09:53.772440] FTL Error while running bot
Npgsql.PostgresException (0x80004005): 42703: column guild.blacklist does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at PluralKit.Core.PKCommand.LogQuery[T](Task`1 task) in /app/PluralKit.Core/Database/Wrappers/PKCommand.cs:line 106
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at PluralKit.Core.Database.ExecuteSqlFile(String resourceName, IPKConnection conn, IDbTransaction tx) in /app/PluralKit.Core/Database/Database.cs:line 126
   at PluralKit.Core.Database.ExecuteSqlFile(String resourceName, IPKConnection conn, IDbTransaction tx) in /app/PluralKit.Core/Database/Database.cs:line 126
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Bot.Init.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /app/PluralKit.Bot/Init.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at PluralKit.Bot.Init.RunWrapper(IContainer services, Func`2 taskFunc) in /app/PluralKit.Bot/Init.cs:line 98
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column guild.blacklist does not exist
    Position: 1072
    File: parse_relation.c
    Line: 3284
    Routine: errorMissingColumn
[2020-07-23 20:09:54.278575] INF Received SIGKILL event, attempting graceful shutdown...
[2020-07-23 20:09:55.903110] INF Connecting to database
[2020-07-23 20:09:56.931953] INF Current schema version: -1
[2020-07-23 20:09:56.933235] INF Applying schema migration 0
[2020-07-23 20:09:56.994216] INF Applying schema migration 1
[2020-07-23 20:09:57.008552] INF Applying schema migration 2
[2020-07-23 20:09:57.022007] INF Applying schema migration 3
[2020-07-23 20:09:57.036384] INF Applying schema migration 4
[2020-07-23 20:09:57.056583] INF Applying schema migration 5
[2020-07-23 20:09:57.069389] INF Applying schema migration 6
[2020-07-23 20:09:57.080369] INF Applying schema migration 7
[2020-07-23 20:09:57.120121] INF Applying schema migration 8
[2020-07-23 20:09:57.224855] FTL Error while running bot
Npgsql.PostgresException (0x80004005): 42703: column guild.blacklist does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at PluralKit.Core.PKCommand.LogQuery[T](Task`1 task) in /app/PluralKit.Core/Database/Wrappers/PKCommand.cs:line 106
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at PluralKit.Core.Database.ExecuteSqlFile(String resourceName, IPKConnection conn, IDbTransaction tx) in /app/PluralKit.Core/Database/Database.cs:line 126
   at PluralKit.Core.Database.ExecuteSqlFile(String resourceName, IPKConnection conn, IDbTransaction tx) in /app/PluralKit.Core/Database/Database.cs:line 126
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Bot.Init.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /app/PluralKit.Bot/Init.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at PluralKit.Bot.Init.RunWrapper(IContainer services, Func`2 taskFunc) in /app/PluralKit.Bot/Init.cs:line 98
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column guild.blacklist does not exist
    Position: 1072
    File: parse_relation.c
    Line: 3284
    Routine: errorMissingColumn
[2020-07-23 20:09:57.726944] INF Received SIGKILL event, attempting graceful shutdown...
```

**Comment by acw0** [comment]
Yeah, that's a weird error. I'm going to try to launch an instance of the legacy bot and update it to latest. Will let you know what happens

**Comment by acw0** [comment]
Hm, so there should be a guild table according to ![this](https://github.com/xSke/PluralKit/blob/main/PluralKit.Core/Database/Functions/functions.sql#L28)

**Comment by acw0** [comment]
These postgres commands *should* get it working: 
```sql
do $$ begin
    create type proxy_tag as (
        prefix text,
        suffix text
    );
exception when duplicate_object then null;
end $$;

alter table members add column display_name text;
alter table members add column proxy_tags proxy_tag[] not null default array[]::proxy_tag[];
alter table members add column keep_proxy bool not null default false;
alter table messages add column original_mid bigint;
```

Do note that it will likely not migrate proxy tags (I'm not sure).

@xSke: What was the required migration between member prefix/suffix columns and the current `proxy_tags` array column?

**Comment by BakaKiller** [comment]
Same message as before :/

```
[2020-07-23 22:21:27.309315] FTL Error while running bot
Npgsql.PostgresException (0x80004005): 42703: column guild.blacklist does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at PluralKit.Core.PKCommand.LogQuery[T](Task`1 task) in /app/PluralKit.Core/Database/Wrappers/PKCommand.cs:line 106
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at PluralKit.Core.Database.ExecuteSqlFile(String resourceName, IPKConnection conn, IDbTransaction tx) in /app/PluralKit.Core/Database/Database.cs:line 126
   at PluralKit.Core.Database.ExecuteSqlFile(String resourceName, IPKConnection conn, IDbTransaction tx) in /app/PluralKit.Core/Database/Database.cs:line 126
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 100
   at PluralKit.Bot.Init.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /app/PluralKit.Bot/Init.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at PluralKit.Bot.Init.RunWrapper(IContainer services, Func`2 taskFunc) in /app/PluralKit.Bot/Init.cs:line 98
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column guild.blacklist does not exist
    Position: 1072
    File: parse_relation.c
    Line: 3284
    Routine: errorMissingColumn
[2020-07-23 22:21:27.810860] INF Received SIGKILL event, attempting graceful shutdown...
```

There also seem to have less relations (and less tables) in the migrated db than in a fresh one :
```
                    List of relations
 Schema |           Name            |   Type   |  Owner
--------+---------------------------+----------+----------
 public | accounts                  | table    | postgres
 public | accounts_system_seq       | sequence | postgres
 public | info                      | table    | postgres
 public | member_guild              | table    | postgres
 public | member_guild_member_seq   | sequence | postgres
 public | member_list               | view     | postgres
 public | members                   | table    | postgres
 public | members_id_seq            | sequence | postgres
 public | members_system_seq        | sequence | postgres
 public | messages                  | table    | postgres
 public | messages_member_seq       | sequence | postgres
 public | servers                   | table    | postgres
 public | switch_members            | table    | postgres
 public | switch_members_id_seq     | sequence | postgres
 public | switch_members_member_seq | sequence | postgres
 public | switch_members_switch_seq | sequence | postgres
 public | switches                  | table    | postgres
 public | switches_id_seq           | sequence | postgres
 public | switches_system_seq       | sequence | postgres
 public | system_fronters           | view     | postgres
 public | system_guild              | table    | postgres
 public | system_guild_system_seq   | sequence | postgres
 public | system_last_switch        | view     | postgres
 public | systems                   | table    | postgres
 public | systems_id_seq            | sequence | postgres
 public | webhooks                  | table    | postgres
(26 rows)
```

**Comment by acw0** [comment]
What's the output of `\d servers`?

**Comment by BakaKiller** [comment]
Ok so after checking, `guild` seems to be built from `servers`. So I compared the migrated `servers` table with the brand new one :
migrated :
```
   Column    |  Type  | Collation | Nullable | Default
-------------+--------+-----------+----------+---------
 id          | bigint |           | not null |
 log_channel | bigint |           |          |
Indexes:
    "servers_pkey" PRIMARY KEY, btree (id)
```

new :
```
       Column        |   Type   | Collation | Nullable |      Default
---------------------+----------+-----------+----------+-------------------
 id                  | bigint   |           | not null |
 log_channel         | bigint   |           |          |
 log_blacklist       | bigint[] |           | not null | ARRAY[]::bigint[]
 blacklist           | bigint[] |           | not null | ARRAY[]::bigint[]
 log_cleanup_enabled | boolean  |           | not null | false
Indexes:
    "servers_pkey" PRIMARY KEY, btree (id)
```

**Comment by acw0** [comment]
Oh that's my bad I forgot to add the servers table migration to my message above :/

**Comment by BakaKiller** [comment]
At least it's not anything too hard ^^

**Comment by BakaKiller** [comment]
Alright, so my psql migration script looks like this :
```sql
do $$ begin
    create type proxy_tag as (
        prefix text,
        suffix text
    );
exception when duplicate_object then null;
end $$;

alter table members add column IF NOT EXISTS display_name text;
alter table members add column IF NOT EXISTS proxy_tags proxy_tag[] not null default array[]::proxy_tag[];
alter table members add column IF NOT EXISTS keep_proxy bool not null default false;
alter table messages add column IF NOT EXISTS original_mid bigint;
alter table servers add column IF NOT EXISTS log_blacklist bigint[] not null default array[]::bigint[];
alter table servers add column IF NOT EXISTS blacklist bigint[] not null default array[]::bigint[];
```
AND IT WORKS !
I tried to add log_cleanup_enabled but it kills the migration process so it's not a good idea.

I will try and make a proxy migration script too, and then I'll close the ticket (and maybe add a "legacyupgrade" folder or somthing ?

**Comment by acw0** [comment]
Glad you got it working!

btw, @xSke: could you put this script on the README of the legacy branch?

**Comment by BakaKiller** [comment]
So, to make a "transition" from old `prefix` and `suffix`, I had to call 
```bash
docker exec -i pluralkit_legacy_db_1 psql -U postgres postgres -tc "select concat('update members set proxy=''{\"(',  prefix, ',', suffix, ')\"}'' where hid=''', hid, ''';') from members where prefix IS NOT NULL OR suffix IS NOT NULL;" > upgrade_proxies.sql
```
That way I had a list of upgrade calls to update everything, but I guess there is an easier way to make it work.
BTW, I also had to remove `prefix` and `suffix` from the migrated table because it made some queries "ambiguous". (I update the citation above to make it take care of this details)

**Comment by BakaKiller** [comment]
Feel free to close after you merge (or reject the merge request and find another way to put it there ^^) :)
Thanks again for your help !
