### ISSUE TITLE
System.TimeoutException: The operation has timed out.

### ISSUE THREAD

**Issue by jbmagination** [xSke/PluralKit#416]
Whenever I attempt to use Docker to run PluralKit, it always errors out:
```
Starting pluralkit_db_1              ... done
Starting pluralkit_scheduled_tasks_1 ... done
Starting pluralkit_redis_1           ... done
Starting pluralkit_bot_1             ... done
Starting pluralkit_api_1             ... done
Starting pluralkit_influx_1          ... done
Attaching to pluralkit_scheduled_tasks_1, pluralkit_db_1, pluralkit_bot_1, pluralkit_api_1, pluralkit_redis_1, pluralkit_influx_1
db_1               | 
db_1               | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1               | 
db_1               | 2022-02-05 21:34:27.183 UTC [1] LOG:  starting PostgreSQL 12.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1               | 2022-02-05 21:34:27.184 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1               | 2022-02-05 21:34:27.184 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1            | 1:C 05 Feb 2022 21:34:28.949 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1            | 1:C 05 Feb 2022 21:34:28.949 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1            | 1:C 05 Feb 2022 21:34:28.949 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1            | 1:M 05 Feb 2022 21:34:28.973 * monotonic clock: POSIX clock_gettime
redis_1            | 1:M 05 Feb 2022 21:34:28.993 * Running mode=standalone, port=6379.
redis_1            | 1:M 05 Feb 2022 21:34:28.993 # Server initialized
redis_1            | 1:M 05 Feb 2022 21:34:28.998 * Ready to accept connections
db_1               | 2022-02-05 21:34:27.191 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1               | 2022-02-05 21:34:28.432 UTC [22] LOG:  database system was interrupted; last known up at 2022-02-05 21:31:16 UTC
influx_1           | ts=2022-02-05T21:34:29.346337Z lvl=info msg="InfluxDB starting" log_id=0ZUxnstW000 version=1.8.10 branch=1.8 commit=688e697c51fd
influx_1           | ts=2022-02-05T21:34:29.346632Z lvl=info msg="Go runtime" log_id=0ZUxnstW000 version=go1.13.8 maxprocs=8
influx_1           | ts=2022-02-05T21:34:29.460516Z lvl=info msg="Using data dir" log_id=0ZUxnstW000 service=store path=/var/lib/influxdb/data
influx_1           | ts=2022-02-05T21:34:29.460774Z lvl=info msg="Compaction settings" log_id=0ZUxnstW000 service=store max_concurrent_compactions=4 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648
influx_1           | ts=2022-02-05T21:34:29.460845Z lvl=info msg="Open store (start)" log_id=0ZUxnstW000 service=store trace_id=0ZUxntL0000 op_name=tsdb_open op_event=start
influx_1           | ts=2022-02-05T21:34:29.550900Z lvl=info msg="Reading file" log_id=0ZUxnstW000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/1/_00001.wal size=40286
influx_1           | ts=2022-02-05T21:34:29.660372Z lvl=info msg="Opened shard" log_id=0ZUxnstW000 service=store trace_id=0ZUxntL0000 op_name=tsdb_open index_version=inmem path=/var/lib/influxdb/data/_internal/monitor/1 duration=130.165ms
influx_1           | ts=2022-02-05T21:34:29.660945Z lvl=info msg="Open store (end)" log_id=0ZUxnstW000 service=store trace_id=0ZUxntL0000 op_name=tsdb_open op_event=end op_elapsed=200.101ms
influx_1           | ts=2022-02-05T21:34:29.661151Z lvl=info msg="Opened service" log_id=0ZUxnstW000 service=subscriber
influx_1           | ts=2022-02-05T21:34:29.661744Z lvl=info msg="Starting monitor service" log_id=0ZUxnstW000 service=monitor
influx_1           | ts=2022-02-05T21:34:29.661776Z lvl=info msg="Registered diagnostics client" log_id=0ZUxnstW000 service=monitor name=build
influx_1           | ts=2022-02-05T21:34:29.661793Z lvl=info msg="Registered diagnostics client" log_id=0ZUxnstW000 service=monitor name=runtime
influx_1           | ts=2022-02-05T21:34:29.661806Z lvl=info msg="Registered diagnostics client" log_id=0ZUxnstW000 service=monitor name=network
influx_1           | ts=2022-02-05T21:34:29.661833Z lvl=info msg="Registered diagnostics client" log_id=0ZUxnstW000 service=monitor name=system
influx_1           | ts=2022-02-05T21:34:29.661925Z lvl=info msg="Starting precreation service" log_id=0ZUxnstW000 service=shard-precreation check_interval=10m advance_period=30m
influx_1           | ts=2022-02-05T21:34:29.661973Z lvl=info msg="Starting snapshot service" log_id=0ZUxnstW000 service=snapshot
influx_1           | ts=2022-02-05T21:34:29.662007Z lvl=info msg="Starting continuous query service" log_id=0ZUxnstW000 service=continuous_querier
influx_1           | ts=2022-02-05T21:34:29.662030Z lvl=info msg="Starting HTTP service" log_id=0ZUxnstW000 service=httpd authentication=false
influx_1           | ts=2022-02-05T21:34:29.662047Z lvl=info msg="opened HTTP access log" log_id=0ZUxnstW000 service=httpd path=stderr
influx_1           | ts=2022-02-05T21:34:29.662229Z lvl=info msg="Storing statistics" log_id=0ZUxnstW000 service=monitor db_instance=_internal db_rp=monitor interval=10s
influx_1           | ts=2022-02-05T21:34:29.662502Z lvl=info msg="Listening on HTTP" log_id=0ZUxnstW000 service=httpd addr=[::]:8086 https=false
influx_1           | ts=2022-02-05T21:34:29.662703Z lvl=info msg="Starting retention policy enforcement service" log_id=0ZUxnstW000 service=retention check_interval=30m
influx_1           | ts=2022-02-05T21:34:29.663504Z lvl=info msg="Listening for signals" log_id=0ZUxnstW000
influx_1           | ts=2022-02-05T21:34:29.663812Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=0ZUxnstW000
db_1               | 2022-02-05 21:34:29.992 UTC [22] LOG:  database system was not properly shut down; automatic recovery in progress
db_1               | 2022-02-05 21:34:30.013 UTC [22] LOG:  redo starts at 0/164DCE0
db_1               | 2022-02-05 21:34:30.014 UTC [22] LOG:  invalid record length at 0/164DD18: wanted 24, got 0
db_1               | 2022-02-05 21:34:30.014 UTC [22] LOG:  redo done at 0/164DCE0
db_1               | 2022-02-05 21:34:30.149 UTC [1] LOG:  database system is ready to accept connections
scheduled_tasks_1  | [21:34:32.925] INF Starting scheduled task runner...
bot_1              | [21:34:34.266] INF Connecting to database
api_1              | [21:34:36.114] WRN Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
api_1              | [21:34:36.181] INF User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
bot_1              | [21:34:38.024] FTL Error while running bot
bot_1              | System.TimeoutException: The operation has timed out.
bot_1              |    at Npgsql.PostgresDatabaseInfo.LoadBackendTypes(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.PostgresDatabaseInfo.LoadPostgresInfo(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.PostgresDatabaseInfoFactory.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.NpgsqlDatabaseInfo.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.NpgsqlConnector.LoadDatabaseInfo(NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
bot_1              |    at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
bot_1              |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
bot_1              | --- End of stack trace from previous location ---
bot_1              |    at PluralKit.Core.Database.Obtain() in /app/PluralKit.Core/Database/Database.cs:line 93
bot_1              |    at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 99
bot_1              |    at PluralKit.Bot.Init.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /app/PluralKit.Bot/Init.cs:line 57
bot_1              | --- End of stack trace from previous location ---
bot_1              |    at PluralKit.Bot.Init.RunWrapper(IContainer services, Func`2 taskFunc) in /app/PluralKit.Bot/Init.cs:line 122
bot_1              | [21:34:38.567] INF Received SIGKILL event, attempting graceful shutdown...
api_1              | [21:34:38.807] INF Now listening on: http://[::]:5000
api_1              | [21:34:38.809] INF Application started. Press Ctrl+C to shut down.
api_1              | [21:34:38.809] INF Hosting environment: Production
api_1              | [21:34:38.809] INF Content root path: /app
bot_1              | [21:34:49.995] INF Connecting to database
bot_1              | [21:34:53.886] FTL Error while running bot
bot_1              | System.TimeoutException: The operation has timed out.
bot_1              |    at Npgsql.PostgresDatabaseInfo.LoadBackendTypes(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.PostgresDatabaseInfo.LoadPostgresInfo(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.PostgresDatabaseInfoFactory.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.NpgsqlDatabaseInfo.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.NpgsqlConnector.LoadDatabaseInfo(NpgsqlTimeout timeout, Boolean async)
bot_1              |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
bot_1              |    at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
bot_1              |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
bot_1              | --- End of stack trace from previous location ---
bot_1              |    at PluralKit.Core.Database.Obtain() in /app/PluralKit.Core/Database/Database.cs:line 93
bot_1              |    at PluralKit.Core.Database.ApplyMigrations() in /app/PluralKit.Core/Database/Database.cs:line 99
bot_1              |    at PluralKit.Bot.Init.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /app/PluralKit.Bot/Init.cs:line 57
bot_1              | --- End of stack trace from previous location ---
bot_1              |    at PluralKit.Bot.Init.RunWrapper(IContainer services, Func`2 taskFunc) in /app/PluralKit.Bot/Init.cs:line 122
bot_1              | [21:34:54.400] INF Received SIGKILL event, attempting graceful shutdown...
pluralkit_bot_1 exited with code 0
```

Not too familiar with Docker, so I don't know what I need to provide to make diagnosing this easier. Trying to test a change I made (will PR if it works)

**Comment by spiralw** [comment]
I'm not sure why this happens - it's happened once in production, but I haven't been able to reproduce it since. I'd recommend installing the dotnet SDK locally for development (you can still run the database in docker)

**Comment by jbmagination** [comment]
Interesting! Will let you know once I get it setup

**Comment by jbmagination** [comment]
After installing .NET locally, it runs just fine now

**Comment by spiralw** [comment]
cool! I'll keep this issue open though, since it is actually a bug
