### ISSUE TITLE
Key error database_uri in config file

### ISSUE THREAD

**Issue by Ryonez** [xSke/PluralKit#55]
When using the database_uri in config, pk will throw a key error.

```
Recreating annabelle-proxy_bot_1 ... done
Recreating annabelle-proxy_api_1 ... done
Attaching to annabelle-proxy_api_1, annabelle-proxy_bot_1
api_1  | Traceback (most recent call last):
api_1  |   File "api_main.py", line 202, in <module>
api_1  |     web.run_app(run())
api_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 53, in run_app
api_1  |     app = loop.run_until_complete(app)
api_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
api_1  |     return future.result()
api_1  |   File "api_main.py", line 197, in run
api_1  |     os.environ["DATABASE_URI"]
api_1  |   File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
api_1  |     raise KeyError(key) from None
api_1  | KeyError: 'DATABASE_URI'
bot_1  | [2019-03-07 17:26:50,556] [discord.client] [WARNING] PyNaCl is not installed, voice will NOT be supported
bot_1  | [2019-03-07 17:26:50,557] [discord.client] [INFO] logging in using static token
annabelle-proxy_api_1 exited with code 1
bot_1  | [2019-03-07 17:26:51,797] [discord.gateway] [INFO] Created websocket connected to wss://gateway.discord.gg?encoding=json&v=
bot_1  | [2019-03-07 17:26:51,799] [discord.gateway] [INFO] Shard ID None has sent the IDENTIFY payload.
api_1  | Traceback (most recent call last):
api_1  |   File "api_main.py", line 202, in <module>
api_1  |     web.run_app(run())
api_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 53, in run_app
api_1  |     app = loop.run_until_complete(app)
api_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
api_1  |     return future.result()
api_1  |   File "api_main.py", line 197, in run
api_1  |     os.environ["DATABASE_URI"]
api_1  |   File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
api_1  |     raise KeyError(key) from None
api_1  | KeyError: 'DATABASE_URI'
bot_1  | [2019-03-07 17:26:52,154] [discord.gateway] [INFO] Shard ID None has connected to Gateway: gateway-prd-main-wrhh, discord-s
api_1  | Traceback (most recent call last):
api_1  |   File "api_main.py", line 202, in <module>
api_1  |     web.run_app(run())
api_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 53, in run_app
api_1  |     app = loop.run_until_complete(app)
api_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
api_1  |     return future.result()
api_1  |   File "api_main.py", line 197, in run
api_1  |     os.environ["DATABASE_URI"]
api_1  |   File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
api_1  |     raise KeyError(key) from None
api_1  | KeyError: 'DATABASE_URI'
annabelle-proxy_api_1 exited with code 1
api_1  | Traceback (most recent call last):
api_1  |   File "api_main.py", line 202, in <module>
api_1  |     web.run_app(run())
api_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 53, in run_app
api_1  |     app = loop.run_until_complete(app)
api_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
api_1  |     return future.result()
api_1  |   File "api_main.py", line 197, in run
api_1  |     os.environ["DATABASE_URI"]
api_1  |   File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
api_1  |     raise KeyError(key) from None
api_1  | KeyError: 'DATABASE_URI'
annabelle-proxy_api_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping annabelle-proxy_api_1   ... done
Stopping annabelle-proxy_bot_1   ... done
```

Using the same uri in `docker-compose.yml` functions correctly.

**Comment by xSke** [comment]
The API container doesn't read from the same configuration file, and just checks the environment variable given in the docker-compose.yml file. I didn't have any specific intentions in mind since I didn't exactly expect anyone to mess with the compose file, so it's not exactly intended behaviour this way :) I could make it read from the config file too, though. Or just split it off into a separate container entirely.

**Comment by Ryonez** [comment]
I see. I have the bot use database I have set up elsewhere, and as I haven't gotten round to setting up an creating apremade docker image to use on the main system, I've just been messing with the dockerfile for now to point it the right server and use the right network.

Why don't you merge the api into the bot proper and have it use a config value to have it enabled/disabled?

**Comment by xSke** [comment]
I'd like to be able to run the API in a separate container (and eventually on a different server entirely) for scalability reasons.

**Comment by Ryonez** [comment]
At the moment it can be run on another server, doesn't it read the bots data from the database?

Maybe this should be split out into it own repo then. And from there docker image creation can be automated. Been thinking about doing that for a while, but the repo here doesn't have tags or version info and some of the changes like this config file does break things.
